#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. ./t/cli/common.sh

# What lives here and not in t/stream-node/tls-passthrough.t: the Test::Nginx
# framework builds its own nginx.conf and never runs apisix/cli/ops.lua or
# ngx_tpl.lua, so the half of this feature that *is* config generation -- how
# listens are grouped by TLS mode, what a passthrough or mixed block renders --
# is unreachable from a .t. The mixed-mode run at the end is here for the same
# reason: its internal unix-socket servers are generated by the template, and
# hand-writing them in a .t would test the copy rather than the template.
#
# Everything a .t can reach -- the preread SNI selecting an upstream, the
# mixed-mode phase picking its target, the `scheme: tls` refusal -- is asserted
# there instead.

# Print the stream server{} block that contains "listen <port>", isolating
# it by brace-counting from each "server {".
block_with_listen() {
    awk -v port="$1" '
    /server[ \t]*\{/ { depth = 0; block = ""; inblock = 1 }
    inblock {
        block = block $0 "\n"
        depth += gsub(/\{/, "{")
        depth -= gsub(/\}/, "}")
        if (depth == 0) {
            if (block ~ ("listen " port "[ ;]")) { printf "%s", block }
            inblock = 0
        }
    }
    ' conf/nginx.conf
}

# Print the stream server{} block whose listen line matches <regex>.
block_with_listen_re() {
    awk -v re="$1" '
    /server[ \t]*\{/ { depth = 0; block = ""; inblock = 1 }
    inblock {
        block = block $0 "\n"
        depth += gsub(/\{/, "{")
        depth -= gsub(/\}/, "}")
        if (depth == 0) {
            if (block ~ re) { printf "%s", block }
            inblock = 0
        }
    }
    ' conf/nginx.conf
}

# Handshake against <port> with <sni>, validating the served chain against
# <ca>. Prints the openssl transcript. Retried by the caller: the stream route
# has to propagate from etcd to the stream worker first.
tls_probe() {
    local port="$1"
    local sni="$2"
    local ca="$3"
    echo -e 'mmm' | timeout 3 openssl s_client -connect 127.0.0.1:"$port" \
        -servername "$sni" -CAfile "$ca" -ign_eof 2>/dev/null
}

# Retry tls_probe under a 20s deadline until one transcript matches every
# pattern given after the CA. All of them have to hold for the same handshake:
# the route reaches the stream workers one at a time, so a probe answered by a
# worker that has already synced says nothing about the next connection.
tls_probe_until() {
    local port="$1" sni="$2" ca="$3"
    shift 3
    local deadline=$(( $(date +%s) + 20 ))
    { set +x; } 2>/dev/null
    while [ "$(date +%s)" -lt "$deadline" ]; do
        local out
        out=$(tls_probe "$port" "$sni" "$ca")
        local matched=1
        local pattern
        for pattern in "$@"; do
            if ! echo "$out" | grep -q "$pattern"; then
                matched=0
                break
            fi
        done
        if [ "$matched" -eq 1 ]; then
            set -x
            return 0
        fi
        sleep 0.3
    done
    set -x
    return 1
}

# === `tls` + `tls_passthrough` on one listen is mixed mode ===
# The port itself can not be both, so it is opened for preread only and the two
# real behaviours move into internal servers the preread phase picks between.
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - addr: 9103
        tls: true
        tls_passthrough: true
' > conf/config.yaml
make init

if block_with_listen 9103 | grep -E "listen 9103[ ;].*ssl" > /dev/null; then
    echo "failed: a mixed listen must stay plain so ssl_preread can see the ClientHello"
    exit 1
fi
if ! block_with_listen 9103 | grep -E "ssl_preread on;" > /dev/null; then
    echo "failed: a mixed listen must enable ssl_preread"
    exit 1
fi
if ! block_with_listen 9103 | grep -E "proxy_pass \\\$stream_tls_target;" > /dev/null; then
    echo "failed: a mixed listen must route to the target the preread phase picked"
    exit 1
fi
if ! block_with_listen 9103 | grep -E "^\s*proxy_protocol on;" > /dev/null; then
    echo "failed: a mixed listen must announce the client across the internal hop"
    exit 1
fi

term_block=$(block_with_listen_re "listen unix:.*stls-t")
pass_block=$(block_with_listen_re "listen unix:.*stls-p")
if ! echo "$term_block" | grep -E "listen unix:.*stls-t.*ssl proxy_protocol;" > /dev/null; then
    echo "failed: the internal terminating server should accept ssl over PROXY protocol"
    exit 1
fi
if ! echo "$term_block" | grep -E "ssl_certificate_by_lua_block" > /dev/null; then
    echo "failed: the internal terminating server should run the certificate phase"
    exit 1
fi
if ! echo "$term_block" | grep -E "set_real_ip_from unix:;" > /dev/null; then
    echo "failed: the internal terminating server should restore the client address"
    exit 1
fi
if ! echo "$pass_block" | grep -E "ssl_preread on;" > /dev/null; then
    echo "failed: the internal passthrough server should preread the ClientHello again"
    exit 1
fi
if echo "$pass_block" | grep -E "ssl_certificate_by_lua_block" > /dev/null; then
    echo "failed: the internal passthrough server must not terminate anything"
    exit 1
fi
if ! echo "$pass_block" | grep -E "set_real_ip_from unix:;" > /dev/null; then
    echo "failed: the internal passthrough server should restore the client address"
    exit 1
fi
if ! block_with_listen 9103 | grep -E "^\s*access_log off;" > /dev/null; then
    echo "failed: the mixed preread block should not log the connection a second time"
    exit 1
fi
echo "passed: tls + tls_passthrough renders a mixed-mode port"

# === Two listens on one address that need different server blocks are rejected ===
# nginx refuses to start over this with reuseport on, and silently keeps only the
# first server with it off.
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - 9100
      - addr: 9100
        tls_passthrough: true
' > conf/config.yaml

out=$(make init 2>&1 || true)
if ! echo "$out" | grep -q "collides with an earlier entry"; then
    echo "failed: the same address in two different server blocks should be rejected"
    exit 1
fi

# The same holds for a port range overlapping a single port.
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - "9100-9110"
      - addr: 9105
        tls_passthrough: true
' > conf/config.yaml

out=$(make init 2>&1 || true)
if ! echo "$out" | grep -q "collides with an earlier entry"; then
    echo "failed: a range overlapping another group should be rejected"
    exit 1
fi

# Same address, same group is untouched.
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - addr: 9100
        tls_passthrough: true
      - addr: 9101
        tls_passthrough: true
' > conf/config.yaml
make init
echo "passed: colliding listens across server blocks are rejected"

# === A passthrough listen renders without ssl, with ssl_preread on ===
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - 9100
      - addr: 9101
        tls: true
      - addr: 9102
        tls_passthrough: true
    udp:
      - 9200
' > conf/config.yaml
make init

if block_with_listen 9102 | grep -E "listen 9102[ ;].*ssl" > /dev/null; then
    echo "failed: a passthrough listen must not carry the ssl flag"
    exit 1
fi
if ! block_with_listen 9102 | grep -E "ssl_preread on;" > /dev/null; then
    echo "failed: a passthrough listen must enable ssl_preread"
    exit 1
fi
if ! block_with_listen 9102 | grep -E "apisix.stream_preread_phase\(true\)" > /dev/null; then
    echo "failed: a passthrough listen must tell the preread phase it is passthrough"
    exit 1
fi
if block_with_listen 9102 | grep -E "ssl_certificate_by_lua_block|proxy_ssl_server_name" > /dev/null; then
    echo "failed: a passthrough listen must not terminate or re-encrypt TLS"
    exit 1
fi
echo "passed: passthrough listen renders ssl_preread without termination"

# === Terminating and plain listens are untouched, and keep their own block ===
if ! block_with_listen 9101 | grep -E "listen 9101[ ;].*ssl" > /dev/null; then
    echo "failed: a tls listen should still terminate"
    exit 1
fi
if ! block_with_listen 9101 | grep -E "ssl_certificate_by_lua_block" > /dev/null; then
    echo "failed: a tls listen should still run the certificate phase"
    exit 1
fi
if block_with_listen 9101 | grep -E "ssl_preread on;" > /dev/null; then
    echo "failed: ssl_preread must not leak into the terminating block"
    exit 1
fi
if ! block_with_listen 9101 | grep -E "listen 9100[ ;]" > /dev/null; then
    echo "failed: plain and tls listens should share one block"
    exit 1
fi
if block_with_listen 9102 | grep -E "listen 9100[ ;]|listen 9200 udp" > /dev/null; then
    echo "failed: the passthrough listen needs a dedicated server block"
    exit 1
fi
if block_with_listen 9102 | grep -E "proxy_pass \\\$stream_tls_target;" > /dev/null; then
    echo "failed: a pure passthrough listen should not pay for the mixed-mode hop"
    exit 1
fi
if grep -E "listen unix:.*stls-" conf/nginx.conf > /dev/null; then
    echo "failed: internal sockets should only exist for mixed listens"
    exit 1
fi
echo "passed: passthrough grouping leaves the other listens alone"

# === A passthrough listen still honours proxy_protocol_to_upstream ===
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - addr: 9102
        tls_passthrough: true
        proxy_protocol_to_upstream: true
' > conf/config.yaml
make init

if ! block_with_listen 9102 | grep -E "ssl_preread on;" > /dev/null; then
    echo "failed: passthrough + proxy_protocol_to_upstream should still preread"
    exit 1
fi
if ! block_with_listen 9102 | grep -E "^\s*proxy_protocol on;" > /dev/null; then
    echo "failed: passthrough + proxy_protocol_to_upstream should still send PROXY"
    exit 1
fi
echo "passed: passthrough combines with proxy_protocol_to_upstream"

# === Mixed mode end to end: one port, the route decides ===
# 9101 terminates its own TLS and is reached untouched; 9102 is plaintext and is
# reached only after the gateway terminates. Same port, same handshake target.
# Both routes are pinned to server_port 9100: the internal servers see a unix
# socket, so these only match if the router reads the address the PROXY header
# carried rather than the socket's own.
echo '
apisix:
  proxy_mode: "http&stream"
  stream_proxy:
    tcp:
      - addr: 9100
        tls: true
        tls_passthrough: true
nginx_config:
  stream_configuration_snippet: |
    server {
        listen 9101 ssl;
        ssl_certificate     ../t/certs/mtls_server.crt;
        ssl_certificate_key ../t/certs/mtls_server.key;
        return "OK FROM PASSTHROUGH BACKEND";
    }
    server {
        listen 9102;
        return "OK FROM TERMINATED BACKEND";
    }
' > conf/config.yaml

make run
wait_for_tcp 127.0.0.1 9180
wait_for_tcp 127.0.0.1 9100

admin_key=$(yq '.deployment.admin.admin_key[0].key' conf/config.yaml | sed 's/"//g')
curl -k -i http://127.0.0.1:9180/apisix/admin/ssls/1 \
    -H "X-API-KEY: $admin_key" -X PUT -d '
{
    "cert": "'"$(cat t/certs/apisix.crt)"'",
    "key": "'"$(cat t/certs/apisix.key)"'",
    "snis": ["test.com"]
}'

curl -k -i http://127.0.0.1:9180/apisix/admin/stream_routes/1 \
    -H "X-API-KEY: $admin_key" -X PUT -d \
    '{"sni":"admin.apisix.dev","server_port":9100,"tls_passthrough":true,"upstream":{"nodes":{"127.0.0.1:9101":1},"type":"roundrobin"}}'
# The whitelist is the assertion that the client address survived the internal
# unix-socket hop: without set_real_ip_from the plugin would see `unix:`.
curl -k -i http://127.0.0.1:9180/apisix/admin/stream_routes/2 \
    -H "X-API-KEY: $admin_key" -X PUT -d \
    '{"sni":"test.com","server_port":9100,"plugins":{"ip-restriction":{"whitelist":["127.0.0.1"]}},"upstream":{"nodes":{"127.0.0.1:9102":1},"type":"roundrobin"}}'

if ! tls_probe_until 9100 admin.apisix.dev t/certs/mtls_ca.crt \
        "OK FROM PASSTHROUGH BACKEND" \
        "CN *= *admin.apisix.dev" \
        "Verify return code: 0 (ok)"; then
    echo "failed: a passthrough route on a mixed port should reach its backend untouched"
    exit 1
fi
echo "passed: mixed port passes through the route that asked for it"

if ! tls_probe_until 9100 test.com t/certs/apisix.crt \
        "OK FROM TERMINATED BACKEND" \
        "CN *= *test.com" \
        "Verify return code: 0 (ok)"; then
    echo "failed: a terminating route on the same port should be served by the gateway"
    exit 1
fi
echo "passed: mixed port terminates the other route, with the client address intact"

# And the client address is really being checked, not merely tolerated.
curl -k -i http://127.0.0.1:9180/apisix/admin/stream_routes/2 \
    -H "X-API-KEY: $admin_key" -X PUT -d \
    '{"sni":"test.com","plugins":{"ip-restriction":{"blacklist":["127.0.0.1"]}},"upstream":{"nodes":{"127.0.0.1:9102":1},"type":"roundrobin"}}'

deadline=$(( $(date +%s) + 20 ))
denied=0
{ set +x; } 2>/dev/null
while [ "$(date +%s)" -lt "$deadline" ]; do
    if ! tls_probe 9100 test.com t/certs/apisix.crt | grep -q "OK FROM TERMINATED BACKEND"; then
        denied=1
        break
    fi
    sleep 0.3
done
set -x
if [ "$denied" -ne 1 ]; then
    echo "failed: blacklisting the real client address should deny the terminating route"
    exit 1
fi
echo "passed: the internal hop reports the real client address, not the socket"

make stop

echo "All stream TLS passthrough tests passed."
