# Configuration for probot-stale - https://github.com/probot/stale

# Label applied when closing
staleLabel: stale

# Configuration settings that are specific to just 'issues' or 'pulls':
pulls:
  daysUntilStale: 60
  daysUntilClose: 28
  limitPerRun: 5
  markComment: >
    This pull request has been marked as stale due to 60 days of inactivity.
    It will be closed in 4 weeks if no further activity occurs. If you think
    that's incorrect or this pull request should instead be reviewed, please simply
    write any comment. Even if closed, you can still revive the PR at any time or
    discuss it on the dev@apisix.apache.org list.
    Thank you for your contributions.
  unmarkComment: >
    This pull request/issue is no longer marked as stale.
  closeComment: >
    This pull request/issue has been closed due to lack of activity. If you think that
    is incorrect, or the pull request requires review, you can revive the PR at any time.

issues:
  daysUntilStale: 350
  daysUntilClose: 14
  markComment: >
    This issue has been marked as stale due to 350 days of inactivity.
    It will be closed in 2 weeks if no further activity occurs. If this issue is still
    relevant, please simply write any comment. Even if closed, you can still revive the
    issue at any time or discuss it on the dev@apisix.apache.org list.
    Thank you for your contributions.
  unmarkComment: >
    This issue is no longer marked as stale.
  closeComment: >
    This issue has been closed due to lack of activity. If you think that
    is incorrect, or the issue requires additional review, you can revive the issue at
    any time.
  # Issues with these labels will never be considered stale.
  exemptLabels:
    - bug
    - enhancement
    - good first issue
