---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qiujiayu.
--- DateTime: 2020/3/16 15:03
---


local all = {
    eureka = {
        instance = {
            --#ip_address:docker宿主机的IP
            --#non_secure_port:docker映射出来的端口
            --#metadata:
        },
        client = {
            service_url = {
                default_zone = "https://xxxxx"
            }
        }
    }
}

local items = all["eureka"]
for i, item in ipairs(items) do
    local id = tostring(i)
    print(id)
    if type(item) ~= "table" then
        data_valid = false
        log.error("invalid item data of [", self.key .. "/" .. id,
                "], val: ", json.delay_encode(item),
                ", it shoud be a object")
    end
end
