deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
nginx_config:
  worker_processes: 2
  error_log_level: warn
apisix:
  enable_control: true
plugins:
  - mollie-health-check
