---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guyang.
--- DateTime: 2020/8/11 4:57 下午
---

local plugin_name = "wosai-console"
local core = require("apisix.core")

local schema = {
    type = "object",
    properties = {
        name = { type = "string" },
    }
}

local _M = {
    version = 0.1,
    priority = 2000,
    name = plugin_name,
    schema = schema,
}

function _M.check_schema(conf)
    return core.schema.check(schema, conf)
end

function _M.log(conf, ctx)
    core.log.info("wosai demo log: " .. conf.name)
end

return _M