name: "Feature request"
description: Ask for a new feature or an improvement of an existing one
title: "feat: As a User, I want to ... so that ..."
body:
  - type: markdown
    attributes:
      value: |
        The more information you fill in, the better we can help you.

        - Please use English on public channel.
        - Encourage using words rather than pictures to describe your demand.
        - Encourage pre-searching with keywords in the issue.
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Provide a clear and concise description of what you want.
    validations:
      required: true
