name: "Request help"
description: Please use this template for requesting help.
title: "request help: "
body:
  - type: markdown
    attributes:
      value: |
        The more information you fill in, the better we can help you.

        - Please use English on public channel.
        - Encourage using words rather than pictures to describe errors.
        - Encourage pre-searching with keywords in the issue.

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Provide a clear and concise description of the help you need.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Request help without environment information will be ignored or closed.
      value: |
        - apisix version (cmd: `apisix version`):
        - OS (cmd: `uname -a`):
        - OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
        - etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
        - apisix-dashboard version, if have:
        - luarocks version, if the issue is about installation (cmd: `luarocks --version`):
    validations:
      required: true
