version: "3.8"

# services:
#   ## Redis cluster
#   redis-cluster:
#     image: vishnunair/docker-redis-cluster:latest
#     restart: unless-stopped
#     ports:
#       - "5000:6379"
#       - "5002:6380"
#       - "5003:6381"
#       - "5004:6382"
#       - "5005:6383"
#       - "5006:6384"

#   ## Redis cluster enable tls
#   redis-cluster2:
#     image: bitnami/redis-cluster:latest
#     restart: unless-stopped
#     ports:
#       - "5000:6379"
#       - "5002:6380"
#       - "5003:6381"
#       - "5004:6382"
#       - "5005:6383"
#       - "5006:6384"
#     environment:
#       - REDIS_TLS_ENABLED=yes
#       - REDIS_TLS_CERT_FILE=/certs/redis.crt
#       - REDIS_TLS_KEY_FILE=/certs/redis.key
#       - REDIS_TLS_CA_FILE=/certs/redisCA.crt
#     volumes:
#       - ./t/certs:/certs

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
      - ./t/certs:/certs
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7000:6379'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
      - ./t/certs:/certs
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7001:6379'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
      - ./t/certs:/certs
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7002:6379'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
      - ./t/certs:/certs
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7003:6379'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
      - ./t/certs:/certs
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7004:6379'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
      - ./t/certs:/certs
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      # - 'REDISCLI_AUTH='
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_TLS_ENABLED=yes'
      - 'REDIS_TLS_CERT_FILE=/certs/redis.crt'
      - 'REDIS_TLS_KEY_FILE=/certs/redis.key'
      - 'REDIS_TLS_CA_FILE=/certs/redisCA.crt'
      - 'REDIS_TLS_AUTH_CLIENTS=no'
    ports:
      - '7005:6379'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local