{
 "title": "Apache APISIX",
 "description": "MicroService API Gateway Apache APISIX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(apisix_http_status,service)"
   },
   {
    "name": "route",
    "query": "label_values(apisix_http_status,route)"
   },
   {
    "name": "instance",
    "query": "label_values(apisix_http_status,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"total\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"accepted\", instance=~\"$instance\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nginx connection state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{instance=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  { "title": "HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Service HTTP Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{code=~\"2..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (status_2xx)",
     "legendFormat": "status_2xx"
    },
    {
     "expr": "sum(rate(apisix_http_status{code=~\"3..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (status_3xx)",
     "legendFormat": "status_3xx"
    },
    {
     "expr": "sum(rate(apisix_http_status{code=~\"4..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (status_4xx)",
     "legendFormat": "status_4xx"
    },
    {
     "expr": "sum(rate(apisix_http_status{code=~\"5..\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (status_5xx)",
     "legendFormat": "status_5xx"
    }
   ]
  }
 ]
}