name: Check performance

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_apisix:
    name: Check performance
    runs-on: ubuntu-latest

    services:
      etcd:
        image: bitnami/etcd:3.4.0
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: install
      run: |
        ~/work/apisix/apisix/utils/check-performance.sh install_dependencies
        ~/work/apisix/apisix/utils/check-performance.sh run_apisix

    - name: test
      run: |
        ~/work/apisix/apisix/utils/check-performance.sh run_test
        ~/work/apisix/apisix/utils/check-performance.sh check_result
