name: Perf

on:
  # only for test
  pull_request:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  perf:
    runs-on: ubuntu-18.04
    timeout-minutes: 90

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Cache deps
        uses: actions/cache@v2.1.7
        env:
          cache-name: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.os_name }}-${{ hashFiles('rockspec/apisix-master-0.rockspec') }}

      - name: Install Dependencies
        run: sudo ./ci/perf.sh install_dependencies

      - name: Install wrk2
        run: sudo ./ci/perf.sh install_wrk2

      - name: Install SystemTap Tools
        run: sudo ./ci/perf.sh install_stap_tools

      - name: Perf Test
        run: ./ci/perf.sh run_perf_test

      - name: Upload perf result
        uses: actions/upload-artifact@v2
        with:
          name: perf.txt
          path: |
            output/perf.txt
          retention-days: 3

      - name: Upload flamegrpah
        uses: actions/upload-artifact@v2
        with:
          name: flamegraph.svg
          path: |
            output/flamegraph.svg
          retention-days: 3
