name: Update pr labels when user responds
permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - name: update label when user responds
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["user responded"]
            })
