name: Cancelling Duplicates
on:
  workflow_run:
    workflows:
      - 'CI'
      - 'CI Centos7'
      - 'Chaos Test'
      - 'fuzzing'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - uses: ./.github/actions/cancel-workflow-runs
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
          skipEventTypes: '["push"]'
